---
- name: Update repositories cache and install Apache
  apt:
    name: apache2
    update_cache: yes

- name: Copy Template
  template:
    src: index.html.j2
    dest: /var/www/html/index.html

- name: Restart Apache
  service: 
    name: apache2
    state: restarted

